### ISSUE TITLE
Problems with instalation in Redmine 3.4.4

### ISSUE THREAD

**Issue by dazebri** [Smile-SA/redmine_smile_list_cf_possible_values_filter#1]
First of all, congratulations for the idea of the plugin. 

The pity is that I'm having problems to install in 3.4.4 version.

First, I installed without problems Redmine - Smile - Base Plugin, but after when I'm executing redmine:plugins:migrate shows the next error:

`Migrating computed_custom_field (Computed custom field)...
Migrating cuckoos (Cuckoos plugin)...
Migrating easy_mindmup (Easy MindMup plugin)...
Migrating easy_wbs (Easy WBS plugin)...
Migrating redmine_agile (Redmine Agile plugin (PRO version))...
Migrating redmine_checklists (Redmine Checklists plugin (PRO version))...
Migrating redmine_cms (Redmine CMS plugin)...
Migrating redmine_filter_assignable (Redmine Filter Assignable plugin)...
Migrating redmine_ics_export (redmine ics export plugin (aka redmics))...
Migrating redmine_issue_dynamic_edit (Redmine Dynamic edit Issue plugin)...
Migrating redmine_issue_favicon (Redmine Issue Favicon plugin)...
Migrating redmine_people (Redmine People plugin (PRO version))...
Migrating redmine_smile_base (Redmine - Smile - Base)...
Migrating redmine_smile_list_cf_possible_values_filter (Redmine - Smile - List CF Possible Values Filter)...
-- [](4.2)
-- [](4.2)
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/icalendar-1.5.3/lib/icalendar/conversions.rb:38: warning: constant ::Fixnum is deprecated
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/icalendar-1.5.3/lib/icalendar/conversions.rb:44: warning: constant ::Bignum is deprecated
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
rake aborted!
NoMethodError: undefined method `[]' for #
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/opt/plesk/ruby/2.4.0/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/plugins/redmine_smile_list_cf_possible_values_filter/db/migrate/20121004160000_add_custom_field_hidden_values.rb:1:in `'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:958:in `block in migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:453:in `migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:466:in `each'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:466:in `migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in '
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/opt/plesk/ruby/2.4.0/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/bin/rake:22:in `load'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/bin/rake:22:in `
'

Caused by:
NoMethodError: undefined method `[]' for #
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/opt/plesk/ruby/2.4.0/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/plugins/redmine_smile_list_cf_possible_values_filter/db/migrate/20121004160000_add_custom_field_hidden_values.rb:1:in `'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1043:in `ddl_transaction'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:453:in `migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:466:in `each'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/redmine/plugin.rb:466:in `migrate'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in '
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/opt/plesk/ruby/2.4.0/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/bin/rake:22:in `load'
/var/www/vhosts/pruebas.i-mes.net/httpdocs/vendor/bundle/ruby/2.4.0/bin/rake:22:in `
'
Tasks: TOP => redmine:plugins:migrate
`

**Here there is the Redmine characteristics:**
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.4.0-p0 (2016-12-24) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  computed_custom_field          1.0.7
  cuckoos                        0.1.0
  easy_mindmup                   1.0
  easy_wbs                       1.5
  redmine_agile                  1.4.5
  redmine_checklists             3.1.10
  redmine_cms                    1.0.1
  redmine_filter_assignable      0.0.1
  redmine_ics_export             3.0.1.dev
  redmine_issue_dynamic_edit     0.7.2
  redmine_issue_favicon          0.0.3
  redmine_people                 1.3.2
  redmine_smile_base             1.0.10
  redmine_stealth                0.7.2
  redmine_zulip                  2.1.2

Thank you in advance for your effort and if you need further info, please tell me.

David

**Comment by Utopism** [comment]
Sorry I had no time to check this issue further.
