### ISSUE TITLE
Plugin installation error

### ISSUE THREAD

**Issue by 6temflex** [Smile-SA/redmine_smile_list_cf_possible_values_filter#2]
Hi, 
I try to install your plugin with redmine 3.3 but this error occurs : 

rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/var/www/html/redmine/base/lib/redmine/plugin.rb:123:in `find'
/var/www/html/redmine/base/lib/redmine/plugin.rb:251:in `requires_redmine_plugin'
/var/www/html/redmine/base/plugins/redmine_smile_list_cf_possible_values_filter-master/init.rb:27:in `block in <top (required)>'

Do you have any idea to solve this problem ?

Thanks a lot

Fab.

**Comment by Utopism** [comment]
Hi,
The plugin folder must have exactly the plugin name : **redmine_smile_list_cf_possible_values_filter**, remove **-master**

**Comment by 6temflex** [comment]
hi yes sorry i've seen that and removed but result is the same : 

bundle exec rake redmine:plugins:migrate NAME=redmine_smile_list_cf_possible_values_filter VERSION=0 RAILS_ENV=production
(in /var/www/html/redmine/base)
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/var/www/html/redmine/base/lib/redmine/plugin.rb:123:in `find'
/var/www/html/redmine/base/lib/redmine/plugin.rb:251:in `requires_redmine_plugin'
/var/www/html/redmine/base/plugins/redmine_smile_list_cf_possible_values_filter/init.rb:27:in `block in <top (required)>'

what is my error ?

**Comment by Utopism** [comment]
Do you have install dependency plugin : **redmine_smile_base** ?

**Comment by 6temflex** [comment]
oh great i missed that step sorry :(

plugin is now active but when trying to access lists custom fields, or project there is an error 500 : 
ActionView::Template::Error (undefined method `timespan_format' for #<Class:0x000000058bf5b0>
Did you mean?  time_format):
    1: <% if User.current.allowed_to?(:view_time_entries, @project) %>
    2:   <h3><%= l(:label_spent_time) %></h3>
    3:   <% if @total_hours.present? %>
    4:     <p><span class="icon icon-time"><%= l_hours(@total_hours) %></span></p>
    5:   <% end %>
    6:   <p>
    7:   <% if User.current.allowed_to?(:log_time, @project) %>
  plugins/redmine_smile_base/lib/smile_redmine_i18n.rb:160:in `format_hours'
  plugins/redmine_smile_base/lib/smile_redmine_i18n.rb:150:in `l_hours'

any clue ?
sorry for that
